"""提示词模板管理模块。"""

from prompts.templates import (
    PLANNER_SYSTEM_PROMPT,
    PLANNER_USER_PROMPT,
    SUMMARIZER_SYSTEM_PROMPT,
    SUMMARIZER_USER_PROMPT,
    CRITIC_SYSTEM_PROMPT,
    CRITIC_USER_PROMPT,
    WRITER_SYSTEM_PROMPT,
    WRITER_USER_PROMPT,
)

__all__ = [
    "PLANNER_SYSTEM_PROMPT",
    "PLANNER_USER_PROMPT",
    "SUMMARIZER_SYSTEM_PROMPT",
    "SUMMARIZER_USER_PROMPT",
    "CRITIC_SYSTEM_PROMPT",
    "CRITIC_USER_PROMPT",
    "WRITER_SYSTEM_PROMPT",
    "WRITER_USER_PROMPT",
]
